name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f Dockerfile.prod -t personal-website:prod . 

  run: 

    needs: build

    runs-on: self-hosted 

    steps:
    - name: Stop currently running container
      continue-on-error: true
      run: docker container stop personal_website

    - name: Run the new container
      run: docker run \
        -d --rm \
        -p 80:80 \
        -p 443:443 \
        --name personal_website personal-website:prod 
